name: WDmodel
channels:
  - defaults
  - http://ssb.stsci.edu/astroconda
  - conda-forge
dependencies:
  - appnope=0.1.0=py36hf537a9a_0
  - args=0.1.0=py36_1000
  - asn1crypto=0.24.0=py36_0
  - atomicwrites=1.3.0=py36_1
  - attrs=19.1.0=py36_1
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - bleach=3.1.0=py36_0
  - ca-certificates=2019.3.9=hecc5488_0
  - cctools=895=1
  - celerite=0.3.0=py36h1702cab_1000
  - certifi=2019.3.9=py36_0
  - cffi=1.12.2=py36hb5b8e2f_1
  - clang=4.0.1=1
  - clang_osx-64=4.0.1=h1ce6c1d_11
  - clangxx=4.0.1=1
  - clangxx_osx-64=4.0.1=h22b1bf0_11
  - clint=0.5.1=py_1
  - cmarkgfm=0.4.2=py36h1de35cc_0
  - compiler-rt=4.0.1=hcfea43d_1
  - corner=2.0.1=py_1001
  - cryptography=2.6.1=py36ha12b0ac_0
  - cryptography-vectors=2.6.1=py_0
  - cycler=0.10.0=py36hfc81398_0
  - decorator=4.4.0=py36_1
  - emcee=2.2.1=pyh24bf2e0_4
  - extinction=0.4.0=py36h7eb728f_0
  - freetype=2.9.1=hb4e5f40_0
  - future=0.17.1=py36_0
  - hdf5=1.10.4=hfa1e0ec_0
  - iminuit=1.3.3=py36h6440ff4_0
  - intel-openmp=2019.3=199
  - ipykernel=5.1.0=py36h39e3cac_0
  - ipython=7.4.0=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36h241746c_0
  - jedi=0.13.3=py36_0
  - joblib=0.13.2=py36_0
  - jupyter_client=5.2.4=py36_0
  - jupyter_core=4.4.0=py36_0
  - kiwisolver=1.0.1=py36h0a44026_0
  - ld64=274.2=1
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libpng=1.6.36=ha441bb4_0
  - libsodium=1.0.16=h3efe00b_0
  - llvm=4.0.1=1
  - llvm-lto-tapi=4.0.1=1
  - mkl=2019.3=199
  - mkl-service=1.1.2=py36hfbe908c_5
  - mkl_fft=1.0.10=py36h5e564d8_0
  - mkl_random=1.0.2=py36h27c97d8_0
  - more-itertools=6.0.0=py36_0
  - mpi=1.0=openmpi
  - mpi4py=3.0.1=py36h27a7d74_0
  - ncurses=6.1=h0a44026_1
  - numpy-base=1.16.2=py36h6575580_0
  - openmpi=3.1.3=h71abe9c_1001
  - openssl=1.1.1b=h01d97ff_2
  - pandas=0.24.2=py36h0a44026_0
  - parso=0.4.0=py_0
  - patsy=0.5.1=py36_0
  - pexpect=4.7.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pkginfo=1.5.0.1=py36_0
  - pluggy=0.9.0=py36_0
  - prompt_toolkit=2.0.9=py36_0
  - psutil=5.6.1=py36h1de35cc_0
  - ptyprocess=0.6.0=py36_0
  - py=1.8.0=py36_0
  - pybind11=2.2.4=py36h04f5b5a_0
  - pycparser=2.19=py36_0
  - pygments=2.3.1=py36_0
  - pymc3=3.5=py36_0
  - pyopenssl=19.0.0=py36_0
  - pyparsing=2.4.0=py_0
  - pysocks=1.6.8=py36_0
  - pysynphot=0.9.12=py36_0
  - pytest=4.4.0=py36_1
  - pytest-arraydiff=0.3=py36h39e3cac_0
  - pytest-astropy=0.5.0=py36_0
  - pytest-doctestplus=0.3.0=py36_0
  - pytest-openfiles=0.3.2=py36_0
  - pytest-remotedata=0.3.1=py36_0
  - python=3.6.8=haf84260_0
  - python-dateutil=2.8.0=py36_0
  - pytz=2019.1=py_0
  - pyzmq=18.0.0=py36h0a44026_0
  - readline=7.0=h1de35cc_5
  - readme_renderer=24.0=py36_0
  - requests-toolbelt=0.9.1=py_0
  - simplegeneric=0.8.1=py36_2
  - six=1.12.0=py36_0
  - sphinx_rtd_theme=0.4.3=py_0
  - sqlite=3.27.2=ha441bb4_0
  - theano=1.0.3=py36h04f5b5a_0
  - tk=8.6.8=ha441bb4_0
  - tornado=6.0.2=py36h1de35cc_0
  - tqdm=4.31.1=py36_1
  - traitlets=4.3.2=py36h65bd3ce_0
  - twine=1.13.0=py_1
  - uncertainties=3.0.3=py36_1000
  - wcwidth=0.1.7=py36h8c6ec74_0
  - webencodings=0.5.1=py36_1
  - wheel=0.33.1=py36_0
  - xz=5.2.4=h1de35cc_4
  - zeromq=4.3.1=h0a44026_3
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - alabaster==0.7.12
    - astropy==3.1
    - babel==2.6.0
    - chardet==3.0.4
    - docutils==0.14
    - h5py==2.8.0
    - idna==2.7
    - imagesize==1.1.0
    - jinja2==2.10
    - markupsafe==1.0
    - matplotlib==2.2.4
    - numpy==1.16.0
    - packaging==18.0
    - pip==18.1
    - requests==2.19.1
    - scipy==1.1.0
    - setuptools==40.6.2
    - snowballstemmer==1.2.1
    - sphinx==1.8.1
    - sphinxcontrib-websupport==1.1.0
    - ticgen==1.0.4
    - urllib3==1.23
prefix: /Users/gnarayan/anaconda3/envs/WDmodel

