name: WDmodel
channels:
  - cburns1
  - mpi4py
  - defaults
  - http://ssb.stsci.edu/astroconda
  - conda-forge
dependencies:
  - args=0.1.0=py36_0
  - ca-certificates=2018.4.16=0
  - celerite=0.3.0=py36_0
  - certifi=2018.4.16=py36_0
  - clint=0.5.1=py36_0
  - corner=2.0.1=py36_0
  - emcee=2.2.1=py36_3
  - extinction=0.3.0=np112py36_0
  - mpi=1.0=mpich
  - mpi4py=3.0.0=py36_0
  - mpich=3.2.1=0
  - openssl=1.0.2o=0
  - pybind11=2.2.3=py36_0
  - uncertainties=3.0.2=py36_1
  - astropy=3.0.2=py36h917ab60_1
  - attrs=18.1.0=py36_0
  - cycler=0.10.0=py36hfc81398_0
  - freetype=2.8=h12048fb_1
  - h5py=2.7.1=py36h39cdac5_0
  - hdf5=1.10.1=ha036c08_1
  - iminuit=1.2=py36h449f2c2_0
  - intel-openmp=2018.0.0=8
  - kiwisolver=1.0.1=py36h792292d_0
  - libcxx=4.0.1=h579ed51_0
  - libcxxabi=4.0.1=hebd6815_0
  - libedit=3.1.20170329=hb402a30_2
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libpng=1.6.34=he12f830_0
  - matplotlib=2.2.2=py36ha7267d0_0
  - mkl=2018.0.2=1
  - more-itertools=4.1.0=py36_0
  - ncurses=6.1=h0a44026_0
  - numpy=1.12.1=py36h8871d66_1
  - pip=10.0.1=py36_0
  - pluggy=0.6.0=py36hb1d0581_0
  - psutil=5.4.5=py36h1de35cc_0
  - py=1.5.3=py36_0
  - pyparsing=2.2.0=py36hb281f35_0
  - pytest=3.5.1=py36_0
  - pytest-arraydiff=0.2=py36_0
  - pytest-astropy=0.3.0=py36_0
  - pytest-doctestplus=0.1.3=py36_0
  - pytest-openfiles=0.3.0=py36_0
  - pytest-remotedata=0.2.1=py36_0
  - python=3.6.5=hc167b69_1
  - python-dateutil=2.7.3=py36_0
  - pytz=2018.4=py36_0
  - readline=7.0=hc1231fa_4
  - scipy=1.1.0=py36hcaad992_0
  - setuptools=39.1.0=py36_0
  - six=1.11.0=py36h0e22d5e_1
  - sqlite=3.23.1=hf1716c9_0
  - tk=8.6.7=h35a86e2_3
  - tornado=5.0.2=py36_0
  - wheel=0.31.1=py36_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=hf3cbc9b_2
  - pysynphot=0.9.12=py36_0
  - openmpi=1.10.2=0
prefix: /Users/gnarayan/anaconda3/envs/WDmodel

